(function($){jQuery.fn.reverse=[].reverse;var defaultInner=0;var defaultOuter=1;var defaultBorders=1;var defaultBegin=0;var minDensity=8;var minDensityLevel1=4;function $orbitlistJS_trace(satellite){while(satellite.length){satellite.addClass('orbitlistJS-trace');satellite=satellite.data('parent');}}
function $orbitlistJS_flatten(core){var coreHeight=core.parents().length;var orbitHeight;core.find('li').reverse().each(function(){var satellite=$(this);var height=(satellite.parents().length-coreHeight+1)/2;satellite.addClass('orbitlistJS-orbit-'+height);satellite.data('height',height);orbitHeight=Math.max(orbitHeight,height);satellite.data('parent',satellite.parent().parent().filter(".orbit li"));core.prepend(satellite);});core.data('coreHeight',coreHeight);core.data('orbitHeight',orbitHeight);core.data('visibleHeight',1);core.find('ul').remove();}
function $orbitlistJS_update(core){var density;var angle;var frameW=core.parent().outerWidth();var frameH=core.parent().outerHeight();var radius=Math.min(frameW,frameH)/2;var offsetTop=frameH/2-radius;var offsetLeft=frameW/2-radius;var orbitHeight=1;var orbit=core.find('.orbitlistJS-orbit-1');var borders=core.data('orbitlistjs-borders');var inner=core.data('orbitlistjs-inner');var outer=core.data('orbitlistjs-outer');var arcBegin=core.data('orbitlistjs-begin');var arcEnd=core.data('orbitlistjs-end');var visibleHeight=core.data('visibleHeight');if(arcEnd<=arcBegin){arcEnd=arcBegin+360;}
var arcLen=(arcEnd-arcBegin)/360;do{if(orbitHeight===1){density=orbit.length;angle=0;}else{var squeeze=3;density=Math.max((orbit.length-1)*squeeze,density);angle=orbit.first().data('parent').data('angle')-1/(density/(orbit.length-1))/2;}
orbit.each(function(index){var satellite=$(this);var distance=(visibleHeight===1?0.5:(borders+orbitHeight-1)/(2*borders+visibleHeight-1));distance=inner+distance*(outer-inner);var radiant=(index/density+angle+arcBegin)*arcLen*Math.PI*2;var vertical=-Math.cos(radiant);var horizontal=Math.sin(radiant);var posTop=radius*distance*vertical*1.5;var posLeft=radius*distance*horizontal*1.5;posTop=posTop+(radius+offsetTop)+core.parent().offset().top-satellite.height()/2;posLeft=posLeft+(radius+offsetLeft)+core.parent().offset().left-satellite.width()/2;satellite.offset({top:posTop,left:posLeft});satellite.data('angle',index/density+angle);});orbitHeight++;orbit=core.find('.orbitlistJS-orbit-'+orbitHeight+':visible');}while(orbit.length);}
$.fn.orbitlist=function(options){var settings=$.extend({onhover:false},options);return this.each(function(index){var core=$(this);core.addClass('orbitlistJS');if(core.data('orbitlistjs-inner')===undefined){core.data('orbitlistjs-inner',defaultInner);}
if(core.data('orbitlistjs-outer')===undefined){core.data('orbitlistjs-outer',defaultOuter);}
if(core.data('orbitlistjs-borders')===undefined){core.data('orbitlistjs-borders',defaultBorders);}
if(core.data('orbitlistjs-begin')===undefined){core.data('orbitlistjs-begin',defaultBegin);}
if(core.data('orbitlistjs-end')===undefined){core.data('orbitlistjs-end',core.data('orbitlistjs-begin'));}
$orbitlistJS_flatten(core);core.find('li').filter(function(){return $(this).data('height')>1;}).hide();var event_handler=function(event){satellite=$(this);if(satellite.hasClass('orbitlistJS-active')){satellite.removeClass('orbitlistJS-active orbitlistJS-trace');satellite.data('parent').addClass('orbitlistJS-active');}else{core.find('li').removeClass('orbitlistJS-active orbitlistJS-trace');satellite.addClass('orbitlistJS-active');$orbitlistJS_trace(satellite);}
var visibleHeight=1;core.find('li').hide();core.find('li').filter(function(index){var parent=$(this).data('parent');var showSatellite=!parent.length|parent.hasClass('orbitlistJS-trace');if(showSatellite){visibleHeight=Math.max(visibleHeight,$(this).data('height'));}
return showSatellite;}).show();core.data('visibleHeight',visibleHeight);$orbitlistJS_update(core);event.stopPropagation();};if(settings['onhover']){core.find('li').mouseover(event_handler);}else{core.find('li').click(event_handler);}
$orbitlistJS_update(core);$(window).resize(function(){$orbitlistJS_update(core);});});};})(jQuery);jQuery(function(){jQuery('ul.orbit').orbitlist({onhover:true});});